###
# This is the place to override the docker cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "docker/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###
# The following shows how to add user ubuntu to the docker group:
#
#normal['docker']['group_members'] = ['ubuntu']
